#!/bin/sh
# Generate every configuration file and boot-directory link from
# config/sun3boot.conf.  Safe to re-run: it rewrites, it does not append.

. "$(dirname -- "$0")/common.sh"

check_clients
SERVER_HOST=$(hostname -s)

# Stamped into the tftpboot entries we write for architectures that have no
# boot program yet, so a later run can recognise and replace its own files.
PLACEHOLDER_MARK='### Sun3_BootDir placeholder, not a boot program ###'

case $CLIENT_MAC in
08:00:20:00:00:00) warn "the first CLIENTS entry still has the placeholder MAC" ;;
esac

mkdir -p "$ETC" "$TFTPBOOT" "$RUN" "$LOG"

# --- etc/ethers -------------------------------------------------------------
# rarpd resolves the second field with gethostbyname(), which short-circuits
# dotted quads, so a literal address avoids needing a name at all.
# /etc/ethers is a symlink to this file (root/grant-privileges.sh).
{
	cat <<-EOF
	# MAC -> IP for rarpd.  /etc/ethers is symlinked here, so this stays editable
	# without root.  Generated by scripts/03-configure.sh -- edit
	# config/sun3boot.conf instead.
	EOF
	clients | while read -r n m i a p; do printf '%s\t%s\n' "$m" "$i"; done
} >"$ETC/ethers"

# --- etc/hosts --------------------------------------------------------------
# Only rpc.bootparamd needs this, and it gets it through a private mount
# namespace (see start.sh).  It reverse-resolves the client in WHOAMI and
# forward-resolves both names in GETFILE, so both directions must be here.
{
	cat <<-EOF
	# Private hosts file, bind-mounted over /etc/hosts for rpc.bootparamd only.
	# Generated by scripts/03-configure.sh.
	127.0.0.1	localhost
	$SERVER_IP	$SERVER_HOST
	EOF
	clients | while read -r n m i a p; do printf '%s\t%s\n' "$i" "$n"; done
} >"$ETC/hosts"

# --- etc/bootparams ---------------------------------------------------------
# netboot asks for "gateway" as well as "root", and uses the address the server
# resolves to as its default route.  Without an entry bootparamd has nothing to
# answer with, so we name this host: on the bridged segment it is the only
# thing the client can reach anyway.  The path is not used for anything --
# bootparamd hands back the address, and "/" is the conventional filler.
{
	cat <<-EOF
	# Answers to the bootparams GETFILE requests netboot makes.
	# Generated by scripts/03-configure.sh.
	EOF
	clients | while read -r n m i a p; do
		printf '%s\troot=%s:%s gateway=%s:/\n' \
			"$n" "$SERVER_HOST" "$NFSROOT/$n" "$SERVER_HOST"
	done
} >"$ETC/bootparams"

# --- etc/exports ------------------------------------------------------------
# Export the client's root directory itself, not its parent: netboot mounts
# exactly the path bootparams handed it, and unfs3 matches export points
# literally rather than walking up to a parent export.
# unfs3 understands ro/rw/root_squash/all_squash/no_root_squash and ignores the
# rest.  Read-only is all the bootloader needs.
# 127.0.0.1 is here so tools/nfs-probe.py can rehearse the mount locally; drop
# it if you would rather nothing but the Sun-3 could read the kernels.  It needs
# "insecure" because unfs3 otherwise demands a source port below 1024, which an
# unprivileged probe cannot get -- the Sun-3's entry keeps that requirement.
{
	echo '# Generated by scripts/03-configure.sh.'
	clients | while read -r n m i a p; do
		printf '%s\t%s(ro,no_root_squash) 127.0.0.1(ro,no_root_squash,insecure)\n' \
			"$NFSROOT/$n" "$i"
	done
} >"$ETC/exports"

# --- tftpboot/ --------------------------------------------------------------
# Drop any name we generated before, so changing a client's address does not
# leave a stale entry behind that rarpd would still happily match on.  Both the
# symlinks and the placeholders below are ours; nothing else here is touched.
find "$TFTPBOOT" -maxdepth 1 -type l -delete
find "$TFTPBOOT" -maxdepth 1 -type f -exec grep -qsF "$PLACEHOLDER_MARK" {} \; -delete
if [ "$PAYLOAD" = custom ]; then
	NETBOOT_SRC=$BOOTDIR/$CUSTOM_NETBOOT
	KERNEL_SRC=$BOOTDIR/$CUSTOM_KERNEL
else
	NETBOOT_SRC=$BOOTDIR/payload/netboot
	KERNEL_SRC=$BOOTDIR/payload/$NETBSD_KERNEL
fi
[ -f "$NETBOOT_SRC" ] || die "$NETBOOT_SRC missing -- run scripts/02-fetch-payload.sh first"
[ -f "$KERNEL_SRC" ]  || die "$KERNEL_SRC missing -- run scripts/02-fetch-payload.sh first"

# An architecture with no boot program still gets its name reserved here, with
# a marker line so a later run can recognise and replace its own file.
write_placeholder() {  # write_placeholder <path> <name> <arch> <ip>
	cat >"$1" <<-EOF
		$PLACEHOLDER_MARK
		Placeholder for $2 ($3) at $4, written by scripts/03-configure.sh.

		There is no boot program for this architecture here yet, so nothing
		will load this file.  It exists to reserve the name and to show the
		client in this directory.
	EOF
}

# --- tftpboot/<HEX> and nfsroot/<client>/ -----------------------------------
# netboot's default kernel name depends on how the PROM is invoked, so provide
# the usual spellings.  All refer to the one kernel we fetched.
#
# Hard links, not symlinks: an NFS READ of a symlink is NFS3ERR_INVAL, so a
# symlinked kernel would force the client through an extra READLINK.  Hard
# links cost nothing here (same filesystem) and keep every name in step --
# including across clients, so a second machine costs no disk.
# Only the names we manage are removed; anything else in a client root (a real
# NFS root, later) is left alone, as is the root of a client you delete from
# the table.
SUN2_NETBOOT=$BOOTDIR/payload/sun2-netboot
SUN2_KERNEL_SRC=$BOOTDIR/payload/sun2-${NETBSD_KERNEL_SUN2:-netbsd-RAMDISK}
SUNOS_BOOT2=$BOOTDIR/payload/sunos-boot.sun2
SUNOS_KERNEL=$BOOTDIR/payload/sunos-vmunix

# Hard links, because an NFS READ of a symlink is an error; see the note above.
link_kernel() {  # link_kernel <source> <client-root> <name...>
	src=$1; root=$2; shift 2
	for k in "$@"; do
		rm -f "$root/$k"
		ln "$src" "$root/$k" 2>/dev/null || cp "$src" "$root/$k"
	done
}

clients | while read -r n m i a p; do
	f=$TFTPBOOT/$(tftpname "$i" "$a")
	mkdir -p "$NFSROOT/$n"
	case $a in
	sun3|sun3x)
		ln -sf "$NETBOOT_SRC" "$f"
		link_kernel "$KERNEL_SRC" "$NFSROOT/$n" \
			netbsd netbsd-rd "$(basename "$KERNEL_SRC")"
		;;
	sun2)
		if [ "$p" = sunos ]; then
			# A different chain entirely.  ND carries only sun2.bb
			# (start.sh passes it to ndbootd); sun2.bb then RARPs and
			# TFTPs this name, so here it is boot.sun2 and atftpd is
			# what serves it.  boot.sun2 mounts the root below over
			# NFS *version 2*, which is why tools/nfs2d.py exists.
			if [ ! -f "$SUNOS_BOOT2" ] || [ ! -f "$SUNOS_KERNEL" ]; then
				warn "SunOS payload missing -- run scripts/02-fetch-payload.sh; $n cannot boot"
				write_placeholder "$f" "$n" "$a" "$i"
				continue
			fi
			ln -sf "$SUNOS_BOOT2" "$f"
			# vmunix is the only name that matters here: it is what
			# the PROM's boot line names and what boot.sun2 reads.
			link_kernel "$SUNOS_KERNEL" "$NFSROOT/$n" vmunix
			# Leave no NetBSD kernel behind to confuse matters.
			rm -f "$NFSROOT/$n/netbsd" "$NFSROOT/$n/netbsd-rd" \
				"$NFSROOT/$n/$(basename "$SUN2_KERNEL_SRC")"
			continue
		fi
		# ndbootd serves the second stage out of this same directory,
		# by the same hex-plus-suffix name a Sun-3 would TFTP.  The
		# first stage is not here: it is the whole of ND blocks 1-15,
		# passed to ndbootd on its command line by start.sh.
		if [ -f "$SUN2_NETBOOT" ]; then
			ln -sf "$SUN2_NETBOOT" "$f"
		else
			write_placeholder "$f" "$n" "$a" "$i"
		fi
		# The sun2 kernel is its own architecture, and its own download.
		# "vmunix" matters: that is the name the PROM passes to netboot
		# by default, and what a Sun-2 asks for before anything else.
		# (NetBSD 10.1 sun2/INSTALL.txt: "hard-linked under the names
		# netbsd and vmunix".)
		if [ -f "$SUN2_KERNEL_SRC" ]; then
			link_kernel "$SUN2_KERNEL_SRC" "$NFSROOT/$n" \
				netbsd vmunix netbsd-rd "$(basename "$SUN2_KERNEL_SRC")"
		else
			warn "$SUN2_KERNEL_SRC missing -- run scripts/02-fetch-payload.sh; $n has no kernel"
		fi
		;;
	*)
		write_placeholder "$f" "$n" "$a" "$i"
		;;
	esac
done

# ----------------------------------------------------------------------------
cat <<EOF

Configured:
  server        $SERVER_HOST $SERVER_IP on $SERVER_IF
  netboot       ${NETBOOT_SRC#"$BOOTDIR"/}
  kernel        ${KERNEL_SRC#"$BOOTDIR"/}

  client    arch   payload  MAC                 IP               boot file
EOF
clients | while read -r n m i a p; do
	printf '  %-9s %-6s %-8s %-19s %-16s %s\n' \
		"$n" "$a" "$p" "$m" "$i" "$(tftpname "$i" "$a")"
done

# RARP is answered over a raw socket, so it works for any address; everything
# after it is routed normally.  A client behind a gateway will therefore get
# its address and then stall, which looks like a TFTP fault and is not one.
clients | while read -r n m i a p; do
	directly_reachable "$i" && continue
	cat >&2 <<-EOF

	warning: $i ($n) is not directly reachable on $SERVER_IF.
	         "ip route get $i" says:
	             $(ip -4 route get "$i" 2>&1 | head -1)
	         RARP will still work -- it is answered on the wire, not routed --
	         but TFTP, bootparams and NFS replies would leave via that route
	         and never arrive.  See README, "More than one client".
	EOF
done

cat <<EOF

At the Sun-3 PROM monitor:  >b le()
EOF

if [ ! -L /etc/ethers ] || [ "$(readlink -f /etc/ethers)" != "$ETC/ethers" ]; then
	cat <<EOF

NOTE: /etc/ethers does not point at etc/ethers yet, so rarpd will not see this
      table.  Have an administrator run root/grant-privileges.sh once.
EOF
fi
