#!/bin/sh
# Unpack a NetBSD 2.0/sun2 root filesystem for a netbooting Sun-2.
#
# Nothing here needs privilege, which is the whole reason it is in scripts/
# rather than beside root/make-sunos-root.sh.  A root filesystem normally
# needs root twice over -- mknod(2) for the 855 device nodes in /dev, and
# chown(2) for the ownership -- and neither happens here:
#
#   /dev   NetBSD's own dev/MAKEDEV prints an mtree(8) specfile with -s, an
#          option it has for building a /dev while cross-building as an
#          ordinary user.  We keep that specfile, put an empty placeholder
#          file where each node belongs, and tools/nfs2d.py --devices reports
#          the placeholders as the nodes the specfile describes.  A device
#          node is a name and a pair of numbers for the client's own kernel
#          to act on; nothing ever reads one over NFS, so that is all of it.
#
#   owner  the tree comes out owned by whoever ran this, and nfs2d is told
#          --squash-to-root, which reports it as owned by root -- which all
#          but 35 of the 3330 files in base.tgz are.  The server can then do
#          the I/O, because it owns the files, and the client sees the
#          ownership NetBSD expects.
#
# This is destructive: it unpacks over whatever is at the destination, and
# replaces /dev entirely.
#
# Usage:  scripts/04-make-netbsd2-root.sh [client-name]
#         defaults to the first netbsd2 client in config/sun3boot.conf

. "$(dirname -- "$0")/common.sh"

NAME=${1:-}
LINE=$(clients | awk -v want="$NAME" \
	'$5 == "netbsd2" && (want == "" || $1 == want) { print; exit }')
[ -n "$LINE" ] || die "no netbsd2 client${NAME:+ called $NAME} in config/sun3boot.conf"

# shellcheck disable=SC2086
set -- $LINE
NAME=$1; IP=$3
DEST=$NFSROOT/$NAME
SERVER_HOST=$(hostname -s)

for s in $NETBSD2_SETS; do
	[ -f "$DIST/netbsd2-$s.tgz" ] \
		|| die "dist/netbsd2-$s.tgz missing -- run scripts/02-fetch-payload.sh first"
done

say "client $NAME at $IP"
say "root   $DEST"

# --- the sets ---------------------------------------------------------------
# -p keeps the mode bits, setuid ones included: nfs2d reports them as they are
# and --squash-to-root makes them setuid to root, which is what they mean.
# Ownership cannot be kept and is not wanted; see the header.
mkdir -p "$DEST"
rm -rf "$DEST/dev"
for s in $NETBSD2_SETS; do
	say "unpacking $s.tgz"
	tar xpzf "$DIST/netbsd2-$s.tgz" -C "$DEST" || die "$s.tgz did not unpack"
done

# --- /dev -------------------------------------------------------------------
[ -f "$DEST/dev/MAKEDEV" ] || die "$DEST/dev/MAKEDEV is missing -- is 'etc' in NETBSD2_SETS?"
say "generating dev/MAKEDEV.spec with NetBSD's own MAKEDEV -s"
( cd "$DEST/dev" && sh ./MAKEDEV -s all >MAKEDEV.spec.new ) \
	|| die "MAKEDEV -s failed"
mv "$DEST/dev/MAKEDEV.spec.new" "$DEST/dev/MAKEDEV.spec"

# One empty file per node, so the name is there to be looked up and listed.
# Their modes on disk are meaningless -- nfs2d answers from the specfile --
# and deliberately not the modes of the nodes, so that nothing on this host
# mistakes one of them for a device it may write to.
( cd "$DEST/dev" && while read -r path type rest; do
	case $type in
	type=dir)             [ "$path" = . ] || mkdir -p "$path" ;;
	type=char|type=block) : >"$path" ;;
	esac
done <MAKEDEV.spec )
say "$(grep -c 'type=char\|type=block' "$DEST/dev/MAKEDEV.spec") device nodes described, placeholders created"

# --- /etc -------------------------------------------------------------------
# rc drops to single user until this is answered, and it ships answered "NO".
sed -i 's/^rc_configured=NO$/rc_configured=YES/' "$DEST/etc/rc.conf"

# /etc/rc.d/root runs "mount /", which needs the root to be in fstab.  The
# spelling has to be the one bootparams hands the kernel, since that is what
# is already mounted there.  (diskless(8).)
cat >"$DEST/etc/fstab" <<EOF
# Generated by scripts/04-make-netbsd2-root.sh.  A diskless client: its root
# is the NFS export bootparamd names, and it has no swap.
$SERVER_HOST:$NFSROOT/$NAME	/	nfs	rw	0 0
EOF

# The kernel already learned the name from bootparams WHOAMI; this is so that
# the userland agrees with it rather than resetting it to "amnesiac".
echo "$NAME" >"$DEST/etc/myname"

# The client cannot resolve either end otherwise: there is no DNS out here.
sed -i '/^# Sun3_BootDir$/,$d' "$DEST/etc/hosts"
cat >>"$DEST/etc/hosts" <<EOF
# Sun3_BootDir
$SERVER_IP	$SERVER_HOST
$IP	$NAME
EOF

say "configured etc/rc.conf, etc/fstab, etc/myname and etc/hosts"

cat <<EOF

$(du -sh "$DEST" 2>/dev/null | cut -f1) in $DEST

Next:
    scripts/03-configure.sh && scripts/stop.sh && scripts/start.sh
    scripts/selftest.sh

root has no password in this release, so the console login is just "root".
EOF
