/* config.h for building ndbootd on Linux/glibc.
 *
 * Upstream ships a config.h generated by autoconf on NetBSD.  Rather than run
 * a 2001-vintage configure, this states the handful of answers that actually
 * differ.  The differences from the NetBSD one are:
 *
 *   HAVE_AF_LINK            no -- Linux reports hardware addresses through
 *                           AF_PACKET/sockaddr_ll, handled in the patch
 *   HAVE_SOCKADDR_SA_LEN    no -- glibc's struct sockaddr has no sa_len
 *   HAVE_NET_IF_ETHER_H     no -- struct ether_header lives in net/ethernet.h
 *   HAVE_SYS_SOCKIO_H       no -- the SIOC* ioctls are in sys/ioctl.h
 *
 * and three things glibc simply does not have, handled in the patch:
 * ether_ntohost lives in <netinet/ether.h>, <time.h> is not pulled in
 * transitively, and reallocarr(3) is NetBSD's alone.
 */

#define STDC_HEADERS 1

/* x86-64 does not require aligned access, and nothing here is built for a
   target that does; leave ALIGNOF_INT32_T at 1 as upstream does. */
#define ALIGNOF_INT32_T 1

/* #undef HAVE_AF_LINK */
/* #undef HAVE_SOCKADDR_SA_LEN */
/* #undef HAVE_STRICT_ALIGNMENT */

#define HAVE_ETHER_NTOHOST 1
#define HAVE_GETDTABLESIZE 1
#define HAVE_SETSID 1
#define HAVE_STRERROR 1

/* #undef HAVE_IOCTLS_H */
#define HAVE_NET_ETHERNET_H 1
/* #undef HAVE_NET_IF_DL_H */
/* #undef HAVE_NET_IF_ETHER_H */
#define HAVE_SYS_IOCTL_H 1
#define HAVE_NETINET_ETHER_H 1
#define HAVE_NETPACKET_PACKET_H 1
#define HAVE_AF_PACKET 1
#define NDBOOTD_NEED_REALLOCARR 1
/* #undef HAVE_SYS_SOCKETIO_H */
/* #undef HAVE_SYS_SOCKIO_H */

#define PACKAGE "ndbootd"
#define VERSION "0.5"
